### ISSUE TITLE
Investigate NLP analysis

### ISSUE THREAD

**Issue by zifeo** [epflbot/epflbot#36]
e.g. https://github.com/golastmile/rasa_nlu

**Comment by mukel** [comment]
Sounds great, what about supporting French?. All the similar (decent) services I know are paid. This could work well since the universe of things is small enough and well defined (names, rooms...)
Ideally we can integrate this to the inline search, that can propose autocompleted commands based on search terms e.g. for "co21" the command "/room CO021"  is proposed.

**Comment by zifeo** [comment]
Might actually be useful: https://github.com/shadaj/scalapy

**Comment by zifeo** [comment]
Another option: https://api.ai just has a free plan (they joined Google).

**Comment by mukel** [comment]
It definitely has the wow effect, conversational and context aware.

**Comment by mukel** [comment]
There's no time budget for this feature and I doubt it will be that useful beyond the wow effect, it's something more like test-once-and-forget.
